# Generated by Django 6.0.7 on 2026-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecolor',
            name='color_hex',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
    ]
