# Generated by Django 6.0.7 on 2026-08-03 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0002_vehiclecolor_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='branch_name',
            field=models.CharField(default='Junagadh', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_no',
            field=models.CharField(blank=True, default='INV-000', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='model_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
