# Generated by Django 6.0.7 on 2026-08-04 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0003_remove_customer_aadhar_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='INV', max_length=10)),
                ('starting_number', models.IntegerField(default=1001)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_sales', models.BooleanField(default=True)),
                ('notify_purchase', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_expenses', models.BooleanField(default=True)),
                ('notify_backup', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_printer', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_size', models.CharField(default='A4', max_length=20)),
                ('default_copies', models.IntegerField(default=1)),
                ('print_preview', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('low_stock_threshold', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Null means global notification for Super Admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='yakuza.branch'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('SYSTEM', 'System'), ('REPORT', 'Report'), ('REMINDER', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['branch', 'is_read', 'notification_type', 'created_at'], name='yakuza_noti_branch__e6b607_idx'),
        ),
        migrations.AddField(
            model_name='backuphistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yakuza.branch'),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printersetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_setting', to=settings.AUTH_USER_MODEL),
        ),
    ]
