# Generated by Django 6.0.7 on 2026-08-06 07:33

import django.db.models.deletion
import django.utils.timezone
import yakuza.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0004_backuphistory_invoicesetting_notificationpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuphistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Backup Histories'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='yakuza_noti_branch__e6b607_idx',
        ),
        migrations.RenameField(
            model_name='invoicesetting',
            old_name='terms_and_conditions',
            new_name='header_text',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify_backup',
            new_name='daily_summary',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify_expenses',
            new_name='email_alerts',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='notify_low_stock',
            new_name='low_stock_alerts',
        ),
        migrations.RenameField(
            model_name='printersetting',
            old_name='default_copies',
            new_name='copies',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='batterycapacity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='invoicesetting',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='invoicesetting',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='invoicesetting',
            name='starting_number',
        ),
        migrations.RemoveField(
            model_name='invoicesetting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_purchase',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='notify_sales',
        ),
        migrations.RemoveField(
            model_name='printersetting',
            name='default_printer',
        ),
        migrations.RemoveField(
            model_name='printersetting',
            name='print_preview',
        ),
        migrations.RemoveField(
            model_name='printersetting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='company_gst',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='invoice_terms',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='systempreference',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='systempreference',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='systempreference',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='vehiclecolor',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='vehiclecompany',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='cgst_percentage',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='sgst_percentage',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yakuza.branch'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='branch_name',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(default='System', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(default='System', max_length=150),
        ),
        migrations.AddField(
            model_name='backuphistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backuphistory',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backuphistory',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[yakuza.validators.validate_aadhar_number]),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default='', max_length=10, validators=[yakuza.validators.validate_mobile_number]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensemaster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_setting', to='yakuza.branch'),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_logos/'),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='show_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printersetting',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_setting', to='yakuza.branch'),
        ),
        migrations.AddField(
            model_name='printersetting',
            name='printer_name',
            field=models.CharField(default='Default Printer', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_backup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='low_stock_threshold',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='settings',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[yakuza.validators.validate_gstin]),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='key',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systempreference',
            name='value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backuphistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yakuza.branch'),
        ),
        migrations.AlterField(
            model_name='backuphistory',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='yakuza.branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='yakuza.branch'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('EXPENSE', 'Expense'), ('LOW_STOCK', 'Low Stock'), ('REMINDER', 'Reminder'), ('SYSTEM', 'System'), ('REPORT', 'Report')], default='SYSTEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='yakuza.branch'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/purchase/'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cgst',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online / UPI'), ('FINANCE', 'Finance'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sgst',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transaction', to='yakuza.stock'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_name',
            field=models.CharField(default='Yakuza EV Showroom', max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='yakuza.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='yakuza.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_records', to='yakuza.sales'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('TRANSIT', 'In Transit'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[yakuza.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[yakuza.validators.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BRANCH_MANAGER', 'Branch Manager'), ('SALES_EXECUTIVE', 'Sales Executive'), ('ACCOUNTANT', 'Accountant')], default='SALES_EXECUTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='base_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='battery_capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yakuza.batterycapacity'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='yakuza.vehiclecompany'),
        ),
    ]
