# Generated by Django 6.0.7 on 2026-08-06 15:16

import yakuza.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0007_invoicesetting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesetting',
            name='user',
        ),
        migrations.AddField(
            model_name='backuphistory',
            name='file_size',
            field=models.CharField(default='0.00 MB', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[yakuza.validators.validate_gstin]),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='authorized_signature',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_signatures/'),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='company_seal',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_seals/'),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='invoice_prefix',
            field=models.CharField(default='INV-2026-', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_delete_days',
            field=models.CharField(default='30', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_format',
            field=models.CharField(default='YYYY-MM-DD', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='decimal_precision',
            field=models.CharField(default='2', max_length=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(default='en-US', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='notification_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.CharField(default='corporate_light', max_length=30),
        ),
        migrations.AddField(
            model_name='settings',
            name='time_format',
            field=models.CharField(default='12h', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
