# Generated by Django on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0009_remove_supplier_contact_person_remove_supplier_email_and_more'),
    ]

    operations = [
        # 1. Remove battery_capacity fields from related models
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='battery_capacity',
        ),
        # 2. Delete BatteryCapacity model
        migrations.DeleteModel(
            name='BatteryCapacity',
        ),
        # 3. Remove fields from Supplier
        migrations.RemoveField(
            model_name='supplier',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='state',
        ),
        # 4. Remove fields from Settings
        migrations.RemoveField(
            model_name='settings',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='language',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='decimal_precision',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='theme',
        ),
        # 5. Remove username from AuditLog
        migrations.RemoveField(
            model_name='auditlog',
            name='username',
        ),
        # 6. Remove email_alerts from NotificationPreference
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_alerts',
        ),
        # 7. Remove fields from InvoiceSetting
        migrations.RemoveField(
            model_name='invoicesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoicesetting',
            name='authorized_signature',
        ),
        migrations.RemoveField(
            model_name='invoicesetting',
            name='company_seal',
        ),
    ]