# Generated by Django 6.0.7 on 2026-08-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0010_database_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/customer/'),
        ),
        migrations.AddField(
            model_name='sales',
            name='invoice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_format',
            field=models.CharField(default='DD-MM-YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', ' UPI'), ('EMI', 'EMI')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='yakuza.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20),
        ),
    ]
