# Generated by Django 6.0.7 on 2026-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0011_remove_auditlog_branch_name_remove_branch_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_no',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
