# Generated by Django 6.0.7 on 2026-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0012_customer_invoice_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='invoice_number',
            new_name='invoice_no',
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('EMI', 'EMI')], default='CASH', max_length=20),
        ),
    ]
