# Generated by Django 6.0.7 on 2026-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0013_rename_invoice_number_sales_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/pdf/'),
        ),
    ]
