# Generated by Django 6.0.7 on 2026-08-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0014_sales_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('REMINDER', 'Reminder')], default='REMINDER', max_length=20),
        ),
    ]
