# Generated by Django 6.0.7 on 2026-08-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0016_alter_auditlog_options_alter_backuphistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='yakuza.branch'),
        ),
    ]
