# Generated by Django 6.0.7 on 2026-08-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0021_seed_initial_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsyncstatus',
            name='branch',
        ),
        migrations.RemoveIndex(
            model_name='syncoutbox',
            name='yakuza_sync_branch__c34cb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='syncoutbox',
            name='yakuza_sync_model_n_153162_idx',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.DeleteModel(
            name='BranchSyncStatus',
        ),
        migrations.DeleteModel(
            name='SyncOutbox',
        ),
    ]
