# Generated by Django 6.0.7 on 2026-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0022_remove_branchsyncstatus_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
