# Generated by Django 6.0.7 on 2026-09-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yakuza', '0024_invoicesequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicesequence',
            options={'verbose_name': 'Invoice Sequence', 'verbose_name_plural': 'Invoice Sequence'},
        ),
    ]
